version: '3.8'

networks:
  traffic-light:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  red-app:
    image: trafficlight/red:v1.0
    container_name: red-app
    networks:
      - traffic-light

  yellow-app:
    image: trafficlight/yellow:v1.0
    container_name: yellow-app
    networks:
      - traffic-light

  green-app:
    image: trafficlight/green:v1.0
    container_name: green-app
    networks:
      - traffic-light

  nginx-load-balancer:
    image: nginx:1.21
    container_name: nginx-load-balancer
    networks:
      - traffic-light
    ports:
      - "3000:3000"
    volumes:
      - ~/nginx/conf.d:/etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - red-app
      - yellow-app
      - green-app
